### ISSUE TITLE
I imported your project into mine and its not compiling !

### ISSUE THREAD

**Issue by skull-candy** [zeeshan-elahi/BarcodeScannerAndCameraXDemo#2]
The Following Errors Are Occuring :

\app\build\generated\data_binding_base_class_source_out\debug\out\com\vns\shopyfycheap\databinding\DrawerBinding.java:4: error: package android.support.design.widget does not exist
import android.support.design.widget.NavigationView;
                                                             ^

**Comment by zeeshan-elahi** [comment]
It is an import issue. You are missing a configuration or dependency setting which I believe you might have already figured out yourself.

Also this is an open source project which I have shared for learning purpose only. It's is available on as it is basics.

**Comment by skull-candy** [comment]
I have not brother, same error ! I am trying to get the dependencies correct, i hope to get it working inshaAllah
